# Generated by Django 2.0.2 on 2018-03-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palsbet', '0003_auto_20180323_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viptipsgames',
            name='cathegory',
            field=models.CharField(choices=[('Vip', 'Vip'), ('Punter Pick', 'Punter Pick'), ('Roll Over', 'Roll Over')], max_length=100),
        ),
    ]
