# Generated by Django 2.0.2 on 2018-03-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palsbet', '0006_auto_20180324_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='pupil',
            new_name='user',
        ),
    ]
