# Generated by Django 2.0.3 on 2018-05-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palsbet', '0008_auto_20180326_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollover',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Published'),
        ),
    ]
