# Generated by Django 2.0.3 on 2018-05-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palsbet', '0009_auto_20180504_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetipsgames',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='punterpick',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='singlebetgames',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='viptips',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Published'),
        ),
    ]
