# Generated by Django 2.0.3 on 2018-06-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palsbet', '0010_auto_20180504_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Head', models.TextField(blank=True, null=True)),
                ('Body', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
            ],
        ),
    ]
