# Generated by Django 2.0.3 on 2018-06-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palsbet', '0011_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jackpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('Number', models.PositiveIntegerField(default=0)),
                ('Home_Team', models.CharField(max_length=200)),
                ('Away_Team', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='freetipsgames',
            name='away_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='freetipsgames',
            name='home_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='punterpick',
            name='away_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='punterpick',
            name='home_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rollover',
            name='away_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rollover',
            name='home_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='singlebetgames',
            name='away_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='singlebetgames',
            name='home_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viptips',
            name='away_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viptips',
            name='home_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
