# Generated by Django 2.0.3 on 2018-06-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palsbet', '0012_auto_20180625_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='jackpot',
            name='Away_Odds',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jackpot',
            name='Draw',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jackpot',
            name='Home_Odds',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jackpot',
            name='Prediction',
            field=models.CharField(choices=[('Running', 'Running'), ('Home', 'Home'), ('Draw', 'Draw'), ('Away', 'Away')], max_length=100, null=True),
        ),
    ]
