# Generated by Django 2.0.3 on 2018-07-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palsbet', '0013_auto_20180625_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notification/%Y/%m/%d'),
        ),
    ]
